services:
  database:
    image: postgres:16-alpine
    container_name: irembo-database
    restart: unless-stopped
    environment:
      - POSTGRES_USER=irembo
      - POSTGRES_PASSWORD=irembo
      - POSTGRES_DB=irembo
    ports:
      - "5420:5432"
    volumes:
      - irembo-data:/var/lib/postgresql/data

volumes:
  irembo-data:
    driver: local
