spring:
  application:
    name: IremboTest
    back-url: ${BACK_URL:http://localhost:8080}

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5420/irembo}
    username: ${DATABASE_USERNAME:irembo}
    password: ${DATABASE_PASSWORD:irembo}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5670}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-change-this-in-production-please-make-it-long-enough}
  expiration: 86400000
